ktor {
  application {
    modules = [org.ayaz.spx500.presentation.ApplicationKt.module]
  }

  development = true

  deployment {
    host = ${?host}
    port = ${?port}
  }

  jwt {
    secretKey = ${?secretKey}
    issuer = ${?issuer}
    audience = ${?audience}
  }
}