ktor {
    application {
        modules = [org.ayaz.exchange.presentation.ApplicationKt.module]
    }

    openApi {
        enabled = true
        codeInferenceEnabled = false
        onlyCommented = true
    }

    development = true

    deployment {
        host = ${?host}
        port = ${?port}
    }

    redis {
        host = ${?rHost}
        post = ${?rPost}
    }

    jwt {
        secretKey = ${?secretKey}
        issuer = ${?issuer}
        audience = ${?audience}
    }
}